// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1561984457);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1561984715);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1561984835);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1561984955);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1561984034);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1561984266);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1561985195);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1561985075);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 819200);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1561983931);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{3c1e9273-224d-478b-a344-e4b8bc3a6d88}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1561964400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1561984722");
user_pref("browser.slowStartup.averageTime", 1368673);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1561984719346");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1561984528);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"87375118-081c-41a2-bfd7-cb162d0025ca\",\"screenshots@mozilla.org\":\"a105dbe3-e161-4629-a078-9018a5bae123\",\"webcompat-reporter@mozilla.org\":\"6ee21453-384c-4eb4-adee-1b5a5865eeee\",\"webcompat@mozilla.org\":\"ccbdbae2-fe4f-460a-bd0b-819e45e016af\"}");
user_pref("idle.lastDailyNotification", 1561985975);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1561984738);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1561985976);
user_pref("places.history.expiration.transient_current_max_pages", 57631);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "5a0d2df9-c2f1-41a3-a56f-1831d0574ec5");
user_pref("security.sandbox.plugin.tempDirSuffix", "30e623ec-65e9-473b-8cc5-640eeaf141ba");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1561985975);
user_pref("toolkit.startup.last_success", 1561983351);
user_pref("toolkit.telemetry.cachedClientID", "f63ad2de-af9a-442c-8f4a-2dc10570bfb4");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
